feeds = [
    ["Front page release announcements", "https://distrowatch.com/news/dw.xml"],
    ["Minor and distribution releases", "https://distrowatch.com/news/dwd.xml"],
    ["Headlines and minor news items", "https://distrowatch.com/news/headline.xml"],
    ["DistroWatch Weekly newsletter", "https://distrowatch.com/news/dww.xml"],
    ["Latest upstream software releases", "https://distrowatch.com/news/dwp.xml"],
    ["DistroWatch podcast (OGG format)", "https://distrowatch.com/news/oggcast.xml"],
    ["DistroWatch podcast (MP3 format)", "https://distrowatch.com/news/podcast.xml"],
    ["Tecmint - Linux Howtos and Tutorials", "https://www.tecmint.com/feed/"],
    ["It's FOSS - Open Source News and Tutorials", "https://itsfoss.com/rss/"],
    ["Linux Journal - Linux News and Articles", "https://www.linuxjournal.com/node/feed"],
    ["Arch Linux - News and Updates", "https://archlinux.org/feeds/news/"],
    ["Linux.com - Linux and Open Source News", "https://www.linux.com/feed/"],
    ["Slashdot - Linux and Open Source News", "https://rss.slashdot.org/Slashdot/slashdotLinux"],
    ["The Linux Foundation Blog", "https://www.linuxfoundation.org/blog/rss/"],
    ["Linux Hint - Linux and FOSS Guides", "https://linuxhint.com/feed/"],
    ["Manjaro Linux - News and Announcements", "https://forum.manjaro.org/c/announcements/12.rss"],
    ["Phoronix - Linux Hardware and Performance", "https://www.phoronix.com/rss.php"],
    ["OSTechNix - Open Source Technology Tutorials", "https://ostechnix.com/feed/"],
    ["SUSE Blog - Enterprise Linux News", "https://www.suse.com/c/feed/"],
    ["Kali Linux - Security and Penetration Testing Tutorials", "https://kalilinux.in/feeds/posts/default"],
    ["Linux Handbook - Server-Side Linux Tutorials", "https://linuxhandbook.com/rss/"],
    ["LinuxTechi - Linux Admin Guides", "https://www.linuxtechi.com/feed/"],
    ["Ubuntu News - Official Updates", "https://insights.ubuntu.com/feed"],
    ["Debian News - Official Updates", "https://www.debian.org/News/news"],
    ["Fedora Magazine - Fedora News and Articles", "https://fedoramagazine.org/feed/"],
    ["LWN.net - Linux Kernel and Open Source News", "https://lwn.net/headlines/newrss"],
    ["GamingOnLinux - Linux Gaming News", "https://www.gamingonlinux.com/article_rss.php"],
    ["DebugPoint - Ubuntu and Linux Tutorials", "https://www.debugpoint.com/feed/"],
    ["SparkyLinux - News and Updates", "https://sparkylinux.org/feed/"],
    ["LinuxLinks - Software and Resource Links", "https://www.linuxlinks.com/feed/"]
]