feeds = [
    ["cdm - create digital music & create digital motion - peter kirn", "https://cdm.link/feed"],
    ["jazz.pt", "https://jazz.pt/feed"],
    ["wire - adventures in modern music", "https://www.thewire.co.uk/home/rss"],
    ["supercollider", "https://sccode.org/rss"],
    ["MaxMSP Reddit", "https://www.reddit.com/r/MaxMSP/.rss"],
    ["Resident Advisor - Electronic Music News", "https://ra.co/xml/news-feed.xml"],
    ["FACT Magazine - Music and Art", "https://www.factmag.com/feed/"],
    ["Electronic Beats - Music and Culture", "https://www.electronicbeats.net/feed/"],
    ["Synthtopia - Synthesizers and Music Tech", "https://www.synthtopia.com/feed"],
    ["MusicTech - Music Production and Tech", "https://www.musictech.com/feed/"],
    ["Attack Magazine - Dance Music Production", "https://www.attackmagazine.com/feed/"],
    ["Sonic Scoop - Audio Engineering and Music Production", "https://sonicscoop.com/feed/"],
    ["Ableton Blog - Music Production and Live", "https://www.ableton.com/en/blog/rss/"],
    ["Sound on Sound - Recording and Music Tech", "https://www.soundonsound.com/rss"],
    ["Cycling '74 - Max/MSP News and Tutorials", "https://cycling74.com/feed"],
    ["SuperCollider GitHub Issues - Development Updates", "https://github.com/supercollider/supercollider/issues.atom"],
    ["XLR8R - Electronic Music and Culture", "https://xlr8r.com/feed/"],
    ["Gearnews - Music Tech and Gear Reviews", "https://www.gearnews.com/feed/"],
    ["The Quietus - Music and Culture", "https://thequietus.com/feed"],
    ["r/SuperCollider Reddit - Community Discussions", "https://www.reddit.com/r/supercollider/.rss"],
    ["Sonicstate - Synths and Music Tech News", "https://www.sonicstate.com/news/rss/"],
    ["Matrixsynth - Synthesizer News and Reviews", "https://www.matrixsynth.com/feeds/posts/default"]
]